image: openjdk:8
vscode:
  extensions:
    - scalameta.metals@1.8.4:cZIFbsTEtuY8//0qEG+XLw==
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
tasks:
- init: source ./gitpod_init.sh
- command: source ./gitpod_command.sh
