image: openjdk:8
vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.7.8:oixMSF1r3cXQPfOQ34+sTA==
tasks:
- init: source ./gitpod_init.sh
- command: source ./gitpod_command.sh
